### ISSUE TITLE
Consider renaming apply_member_pointer

### ISSUE THREAD

**Issue by ldionne** [boostorg/callable_traits#136]
I think I'm struggling to understand what `apply_member_pointer` because of its name. Instead, I think something along the lines of `make_member` (the intent is that you're making a non-member signature into a member signature) might be more intuitive. Just a suggestion.

**Comment by badair** [comment]
Relates to #110

**Comment by badair** [comment]
Thanks, Louis. You're right, this one is a bit weird.
